version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: wec-postgres
    environment:
      POSTGRES_DB: wecover
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d wecover"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wec-network
    restart: unless-stopped

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: wec-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: "http://localhost,http://localhost:3000,http://localhost:5173"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - wec-network
    restart: unless-stopped

  # MinIO bucket setup (runs once)
  minio-setup:
    image: minio/mc:latest
    container_name: wec-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/wecover-pdfs --ignore-existing;
      /usr/bin/mc anonymous set public myminio/wecover-pdfs;
      exit 0;
      "
    networks:
      - wec-network

  # API Service
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: wec-api
    environment:
      NODE_ENV: production
      PORT: 5173
      HOST: 0.0.0.0
      LOG_LEVEL: info
      DATABASE_URL: postgres://user:pass@postgres:5432/wecover
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: wecover-pdfs
      S3_REGION: us-east-1
      PRODUCT_VERSION: WEC-PS-VSC-09-2025
      PDF_TEMPLATE_KEY: templates/ContractPSVSCTemplate_HT_v07_Form.pdf
      PLAYWRIGHT_CHROMIUM_EXECUTABLE: /usr/bin/chromium-browser
      CORS_ORIGIN: http://localhost
    ports:
      - "5173:5173"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - wec-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5173/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web Application
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: wec-web
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    networks:
      - wec-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  wec-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
